import Head from "next/head";
import { projectsData } from "../data/data";
import Hero from "@/components/Hero/Hero";
import Projects from "@/components/Projects/Projects";
import About from "@/components/About/About";
import Contact from "@/components/Contact/Contact";
import Skills from "@/components/Skills/Skills";
import { motion } from "framer-motion";
import { staggerContainer } from "@/utils/motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Beatrice Stanila Porftolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.svg" />
      </Head>
      <main className="main">
        <Hero
          greeting="Hi there! My name is .."
          name="Beatrice Stanila"
          intro="A software developer excited to  build technologies solutions to problems."
        />
        <About />
        <div className="projects" id="projects">
          <div>
            <h3 className="projects-header">My projects</h3>
            <motion.div
              className="projects-wrapper"
              variants={staggerContainer}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: 0.25 }}
            >
              {projectsData.map((data, index) => {
                return (
                  <Projects
                    title={data.project_name}
                    description={data.project_description}
                    stack={data.stack_used}
                    demo={data.demo_link}
                    repo={data.repo_link}
                    image={data.image}
                    key={data.project_name}
                    index={index}
                  />
                );
              })}
            </motion.div>
          </div>
        </div>

        <Skills />
        <Contact />
      </main>
    </>
  );
}
