import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";

import Hero from "@/components/Hero/Hero";
import Projects from "@/components/Projects/Projects";

export default function Home() {
  const [projectData, setProjectData] = useState([]);

  const dataURL = "http://localhost:4000/";

  useEffect(() => {
    axios.get(dataURL).then((response) => {
      console.log(response.data);
      setProjectData(response.data);
    });
  }, []);
  console.log(projectData);
  return (
    <>
      <Head>
        <title>Beatrice Stanila Porftolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Hero
          greeting="Hi there! My name is .."
          name="Beatrice Stanila"
          intro="A software developer excited to  build technologies solutions to problems."
        />

        {projectData.map((el) => {
          return (
            <Projects
              title={el.title}
              description={el.description}
              demo={el.demo}
              repo={el.repo}
              key={el._id}
            />
          );
        })}
      </main>
    </>
  );
}
