import Head from "next/head";
// import styles from "@/styles/Home.module.css";

import Hero from "@/components/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Beatrice Stanila Porftolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Hero
          greeting="Hi there! My name is .."
          name="Beatrice Stanila"
          intro="A software developer excited to  build technologies solutions to problems."
        />
      </main>
    </>
  );
}
